@echo off
echo Starting Nydra Intelligence...
echo Starting Backend Engine (Port 8000)...
start /b .\.venv\Scripts\python.exe -m uvicorn api:app --port 8000
echo Starting Frontend UI (Port 3000)...
cd frontend
npm run dev
pause
